name: Project Automation

on:
  issues:
    # run this action when the following events occurs on an issue
    types: [opened, closed, reopened, labeled, unlabeled, connected]
  pull_request:
    # run this action when the following events occurs on a pull request
    types:
      [
        opened,
        closed,
        reopened,
        labeled,
        unlabeled,
        ready_for_review,
        review_requested,
        review_request_removed,
        review_dismissed,
        reviewed,
        merged,
      ]
env:
  MY_GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}

jobs:
  features_project:
    runs-on: ubuntu-latest
    name: Add into "Features" Project
    # A "Issue" or "Pull Request" will go into "Features" project only if:
    # 1. The "Issue" has "feature_request" label
    # 2 The "Pull Request" has "feature" label
    if: |
      contains(github.event.issue.labels.*.name, 'feature_request') ||
      contains(github.event.pull_request.labels.*.name, 'feature')
    steps:
      - name: Add to "To do" column
        # A "Issue" or "Pull Request" will be added in "To do" colum only if:
        # 1. The "Issue" was newly opened, reopened or labels were updated
        # 2. No "Pull Requests" should be in "To do" column
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event.action == 'opened' ||
          github.event.action == 'reopened' ||
          github.event.action == 'labeled' ||
          github.event.action == 'unlabeled'
        with:
          project: "https://github.com/orgs/hugo-toha/projects/1"
          column_name: "To do"
